package com.framework.enums;

public enum ConfigProperties {
	
	BROWSER,
	URL,
	OVERRIDEREPORT,
	TAKESCREENSHOT,
	PASSEDSTEPSCREENSHOT,
	FAILEDSTEPSCREENSHOT,
	SKIPPEDSTEPSCREENSHOT,
	RETRYFAILEDTESTS,
	RUNMODE
}
